Added pools styling
galacticcouncil/Hydra-mining-ui pull request #50
Opened 2022-12-08 10:11 UTC by vkulinich-cl

2022-12-08 12:20 UTC, obsivac-cleevio requested changes

2022-12-08 12:20 UTC, obsivac-cleevio commented on src/sections/pools/modals/AddLiquidity/AddLiquidity.tsx
> +            0.15%
radsi napsat TODO misto hodnoty, at se na to nezapomene

2022-12-08 12:20 UTC, obsivac-cleevio commented on src/sections/pools/modals/AddLiquidity/AddLiquidity.tsx
> +          Position Details
do `translations`

2022-12-08 13:37 UTC, vkulinich-cl commented on src/components/Input/Input.styled.ts
> +    color: rgba(114, 131, 165, 0.6);
nie, to nema ani nazev konstanty ve figme, proto jsem nechtel vymyslet novou barvu

2022-12-08 13:38 UTC, vkulinich-cl commented on src/components/Slider/Slider.styled.ts
> +  background-color: rgba(150, 138, 158, 0.24);
tady to stejny

2022-12-09 08:59 UTC, obsivac-cleevio approved these changes

2022-12-09 08:59 UTC, merged